global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgresql_exporter'
    static_configs:
      - targets: ['postgresql_exporter:9187']